title: Modelling the transmission of aquatic pathogens
logo: /assets/img/SalmonViruses-02.jpeg
description: Some details about a project on mathematical modelling of the transmission of aquatic pathogens in fish populations
remote_theme: pages-themes/slate@v0.2.0
google_analytics: UA-1943806-8
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
