title: Modelling the transmission of aquatic pathogens
logo: /assets/img/Gemini_Generated_Image_z9pgyz9pgyz9pgyz.png
description: Some details about a project on mathematical modelling of the transmission of aquatic pathogens in fish populations
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
